
name: sirf-build
channels:
  - conda-forge
dependencies:
# --- Essential build tools with compatible GCC ---
  - gcc_linux-64=11.*  # Pin to GCC 11 for compatibility
  - gxx_linux-64=11.*  # Pin to G++ 11 for compatibility
  - gfortran_linux-64=11.*  # Pin to gfortran 11
  - python=3.10
  - cmake>=3.16,<4.0
  - git
  - pkg-config
  - ninja
  - make
  - ccache
# --- Core scientific stack ---
  - numpy>=1.18.0,<2.0
  - scipy
  - matplotlib
  - h5py
# --- Essential SIRF deps ---
  - boost
  - boost-cpp  # Ensure C++ headers are available
  - fftw
  - swig=4.0.*
  - armadillo
  - eigen
  - itk
  - pugixml
# -hdf5
# --- CUDA (using available packages) ---
  - cudatoolkit>=11.0 # Runtime libraries
  - cupy # Let conda resolve compatible version
  # Note: nvcc typically comes from system installation
# --- Parallelproj requirements ---
  - parallelproj>=1.10
  - libparallelproj>=1.10
# --- Minimal extras ---
  - deprecation
  - nibabel
  - pillow
  - tk
  - qt=5.*  # Pin to Qt 5 for compatibility
# --- pip for packages not in conda ---
  - pip
  - pip:
    - pydicom