name: sirf-build
channels:
  - https://software.repos.intel.com/python/conda  # For CIL
  - conda-forge
  - ccpi  # For CIL package
dependencies:
# --- Essential build tools ---
  - compilers  # Back to general compilers package
  - python=3.10
  - cmake>=3.16,<4.0
  - git
  - pkg-config
  - ninja
  - make
  - ccache
# --- Core scientific stack ---
  - numpy<2.0
  - scipy
  - matplotlib
  - h5py
# --- Essential SIRF deps ---
  - boost
  - boost-cpp  # Ensure C++ headers are available
  - fftw
  - swig<=4.0.*
  - armadillo
  - eigen
  - itk
  - pugixml
# -hdf5
# --- CUDA (using available packages) ---
  - cudatoolkit>=11.0 # Let conda choose available version
  - cupy # Let conda resolve compatible version
# --- CIL (install via conda to avoid build issues) ---
  - cil=25.0.0  # Core Imaging Library version 25.0.0
# --- Parallelproj requirements ---
  - parallelproj>=1.10
  - libparallelproj>=1.10
# --- Minimal extras ---
  - nibabel
  - pillow
  - tk
  - qt=5.*  # Pin to Qt 5 for compatibility
# --- pip for packages not in conda ---
  - pip
  - pip:
    - pydicom